from __future__ import annotations

MODULE_PACKS: dict[str, list[str]] = {
    "pack.core_federal": [
        "fetch.census.acs_profile",
        "fetch.bls",
        "fetch.bea.nipa_table",
        "fetch.fred.series",
        "fetch.hud.fmr",
    ],
    "pack.federal_extended": [
        "fetch.census.acs_profile",
        "fetch.bls",
        "fetch.bea.nipa_table",
        "fetch.fred.series",
        "fetch.hud.fmr",
        "fetch.treasury.fiscal_data",
        "fetch.usaspending.awards",
        "fetch.congress.bills",
        "fetch.federal_register.documents",
        "fetch.regulations.dockets",
        "fetch.usgs.earthquakes",
        "fetch.noaa.cdo",
        "fetch.eia.series",
        "fetch.fbi.crime",
        "fetch.nhtsa.recalls",
        "fetch.fema.openfema",
        "fetch.cdc",
        "fetch.cms.data",
        "fetch.usda.quickstats",
    ],
    "pack.civic_socrata": [
        "fetch.socrata.dataset",
        "fetch.socrata.chicago_crimes",
        "fetch.nyc_open_data",
        "fetch.socrata.sf_building_permits",
        "fetch.socrata.la_crime",
        "fetch.socrata.seattle_building_permits",
    ],
    "pack.federal_research": [
        "fetch.college_scorecard.schools",
        "fetch.naep.adhoc_data",
        "fetch.dol.osha_inspections",
        "fetch.epa.echo_facilities",
        "fetch.epa.aqs_annual",
        "fetch.fdic.institutions",
        "fetch.fec",
        "fetch.gsa_calc.ceiling_rates",
        "fetch.uspto.application",
        "fetch.cfpb.complaints",
        "fetch.usda.fooddata_search",
        "fetch.sec.company_submissions",
        "fetch.clinical_trials.studies",
        "fetch.fda.drug_events",
        "fetch.doj.press_releases",
        "fetch.nrel.alt_fuel_stations",
        "fetch.open_payments.datasets",
        "fetch.world_bank",
    ],
    "pack.global_economic": [
        "fetch.world_bank",
        "fetch.fred.series",
        "fetch.bea.nipa_table",
        "fetch.bls",
        "fetch.treasury.fiscal_data",
        "fetch.usaspending.awards",
    ],
    "pack.us_housing": [
        "fetch.hud.fmr",
        "fetch.census.acs_profile",
        "fetch.nyc_open_data",
        "fetch.socrata.sf_building_permits",
        "fetch.socrata.seattle_building_permits",
    ],
    "pack.public_health": [
        "fetch.ahrq.meps",
        "fetch.ahrq.nhqdr",
        "fetch.ahrq.sdoh",
        "fetch.airnow",
        "fetch.atsdr.eji",
        "fetch.atsdr.svi",
        "fetch.atus",
        "fetch.brfss",
        "fetch.cdc",
        "fetch.cdc.biomonitoring",
        "fetch.cdc.birth_defects",
        "fetch.cdc.heat_events",
        "fetch.cdc.mmwr",
        "fetch.cdc.nhanes",
        "fetch.cdc.nhis",
        "fetch.cdc.nsfg",
        "fetch.cdc.nvss",
        "fetch.cdc.nwss",
        "fetch.cdc.places",
        "fetch.cdc.ssun",
        "fetch.cdc.tracking",
        "fetch.cdc.vaxview",
        "fetch.cdc.wisqars",
        "fetch.cdc.wonder",
        "fetch.cejst",
        "fetch.census.acs_profile",
        "fetch.census.cps",
        "fetch.census.decennial",
        "fetch.census.htops",
        "fetch.census.onthemap_em",
        "fetch.census.sipp",
        "fetch.cms.data",
        "fetch.cms.cciio",
        "fetch.cms.marketplace_reports",
        "fetch.cms.medicaid",
        "fetch.cms.synpuf",
        "fetch.clinical_trials.studies",
        "fetch.dol.naws",
        "fetch.ed.crdc",
        "fetch.epa.aqs_annual",
        "fetch.epa.echo_facilities",
        "fetch.epa.ejscreen",
        "fetch.epa.enviroatlas",
        "fetch.epa.iris",
        "fetch.epa.smart_location",
        "fetch.epa.tri",
        "fetch.fema.nri",
        "fetch.fda.drug_events",
        "fetch.hhs.poverty_guidelines",
        "fetch.hrsa.ahrf",
        "fetch.hrsa.hpsa",
        "fetch.hrsa.nsch",
        "fetch.hrsa.uds",
        "fetch.hud.hdx_homelessness",
        "fetch.naep.adhoc_data",
        "fetch.noaa.cmra",
        "fetch.noaa.nws",
        "fetch.open_payments.datasets",
        "fetch.umich.nanda",
        "fetch.usda.food_access",
        "fetch.usda.food_security",
        "fetch.usda.fooddata_search",
    ],
    "pack.health_equity": [
        "fetch.ahrq.sdoh",
        "fetch.atsdr.eji",
        "fetch.atsdr.svi",
        "fetch.cejst",
        "fetch.census.acs_profile",
        "fetch.census.decennial",
        "fetch.census.htops",
        "fetch.ed.crdc",
        "fetch.epa.ejscreen",
        "fetch.hhs.poverty_guidelines",
        "fetch.hud.hdx_homelessness",
        "fetch.umich.nanda",
        "fetch.usda.food_access",
    ],
    "pack.health_environment": [
        "fetch.airnow",
        "fetch.cdc.heat_events",
        "fetch.cdc.nwss",
        "fetch.cdc.tracking",
        "fetch.epa.aqs_annual",
        "fetch.epa.echo_facilities",
        "fetch.epa.enviroatlas",
        "fetch.epa.iris",
        "fetch.epa.smart_location",
        "fetch.epa.tri",
        "fetch.fema.nri",
        "fetch.noaa.cmra",
        "fetch.noaa.nws",
    ],
    "pack.health_surveys": [
        "fetch.ahrq.meps",
        "fetch.atus",
        "fetch.brfss",
        "fetch.cdc.nhanes",
        "fetch.cdc.nhis",
        "fetch.cdc.nsfg",
        "fetch.census.cps",
        "fetch.census.sipp",
        "fetch.hrsa.nsch",
    ],
    "pack.healthcare_access": [
        "fetch.ahrq.nhqdr",
        "fetch.cdc.places",
        "fetch.cms.cciio",
        "fetch.cms.data",
        "fetch.cms.marketplace_reports",
        "fetch.cms.medicaid",
        "fetch.cms.synpuf",
        "fetch.hrsa.ahrf",
        "fetch.hrsa.hpsa",
        "fetch.hrsa.uds",
        "fetch.open_payments.datasets",
    ],
    "pack.health_access_helpers": [
        "fetch.nih.usrds",
        "fetch.nlm.vsac",
    ],
    "pack.environment_climate": [
        "fetch.noaa.cdo",
        "fetch.usgs.earthquakes",
        "fetch.epa.aqs_annual",
        "fetch.airnow",
        "fetch.epa.echo_facilities",
        "fetch.eia.series",
        "fetch.nrel.alt_fuel_stations",
        "fetch.fema.openfema",
    ],
    "pack.civic_transparency": [
        "fetch.congress.bills",
        "fetch.federal_register.documents",
        "fetch.regulations.dockets",
        "fetch.usaspending.awards",
        "fetch.fec",
        "fetch.sec.company_submissions",
        "fetch.cfpb.complaints",
        "fetch.gsa_calc.ceiling_rates",
        "fetch.doj.press_releases",
    ],
    "pack.provider_kits": [
        "fetch.world_bank",
        "fetch.nyc_open_data",
        "fetch.fec",
        "fetch.cdc",
        "fetch.bls",
    ],
    "pack.global_governance": [
        "fetch.vdem",
        "fetch.wgi",
        "fetch.wjp_rule_of_law",
        "fetch.rsf_press_freedom",
        "fetch.ti_cpi",
        "fetch.fsi",
        "fetch.gpi",
        "fetch.un_egdi",
    ],
    "pack.global_development": [
        "fetch.undp_hdr",
        "fetch.sdg_index",
        "fetch.oecd_sdmx",
        "fetch.oecd_dac_crs",
        "fetch.iati",
        "fetch.imf_cdis",
        "fetch.nd_gain",
    ],
    "pack.global_data_hubs": [
        "fetch.owid_charts",
        "fetch.owid_catalog",
        "fetch.overture_maps",
    ],
    "pack.global_surveys": [
        "fetch.wvs",
        "fetch.pew",
        "fetch.atus",
        "fetch.brfss",
    ],
    "pack.international_core": [
        "fetch.world_bank",
        "fetch.vdem",
        "fetch.wgi",
        "fetch.undp_hdr",
        "fetch.ti_cpi",
        "fetch.owid_charts",
        "fetch.oecd_sdmx",
    ],
    "pack.geospatial": [
        "fetch.natural_earth",
        "fetch.earthengine",
        "fetch.planetary_computer",
        "fetch.earthdata",
        "fetch.overture_maps",
    ],
}


# One-liner descriptions so packs are discoverable by topic. Keep these
# in language a non-coder would type into a chat ("public health",
# "international", "housing") so `sancho find sources` can rank them
# alongside individual modules.
PACK_DESCRIPTIONS: dict[str, str] = {
    "pack.core_federal": "Core US federal economic data: Census ACS, BLS labor, BEA national accounts, FRED Federal Reserve series, HUD rents.",
    "pack.federal_extended": "Extended US federal: core_federal plus Treasury, USAspending, Congress bills, Federal Register, regulations dockets, USGS earthquakes, NOAA climate, EIA energy, FBI crime, NHTSA vehicle recalls, FEMA disasters, CDC, CMS, USDA agriculture.",
    "pack.federal_research": "US federal research-oriented sources: College Scorecard, NAEP education, OSHA inspections, EPA enforcement / air quality, FDIC banks, FEC campaign finance, GSA contracts, USPTO patents, CFPB complaints, USDA FoodData, SEC EDGAR, ClinicalTrials.gov, openFDA, DOJ press releases, NREL alt fuel, Open Payments, World Bank.",
    "pack.civic_socrata": "US city open-data portals on Socrata: generic Socrata client + Chicago, NYC, SF, Seattle, LA crime / permits.",
    "pack.civic_transparency": "Government accountability + transparency: Congress, Federal Register, regulations.gov, USAspending, FEC, SEC EDGAR, CFPB complaints, GSA contracts, DOJ press releases.",
    "pack.us_housing": "US housing affordability + supply: HUD FMR, Census ACS, NYC + SF + Seattle building permits.",
    "pack.global_economic": "Macro + development indicators: World Bank, FRED, BEA, BLS, Treasury, USAspending.",
    "pack.public_health": "Broad public-health bundle: AHRQ (3 modules), AirNow, ATSDR (2), ATUS, BRFSS, CDC (15), CEJST, Census health series (5), CMS (6), DOL NAWS, Ed CRDC, EPA health (8), FEMA NRI, FDA, HHS poverty, HRSA (4), HUD HDX homelessness, NAEP, NOAA (2), Open Payments, UMich NANDA, USDA food data (3).",
    "pack.health_equity": "Health equity and social context: AHRQ SDOH, ATSDR EJI+SVI, CEJST, Census ACS+Decennial+HTOPS, Ed CRDC, EPA EJScreen, HHS poverty, HUD HDX homelessness, UMich NANDA, USDA food access.",
    "pack.health_environment": "Environmental health and resilience: AirNow, CDC heat events, CDC wastewater, CDC environmental tracking, EPA AQS/ECHO/EnviroAtlas/IRIS/Smart Location/TRI, FEMA NRI, NOAA CMRA, NOAA NWS.",
    "pack.health_surveys": "Health survey microdata: AHRQ MEPS, ATUS, BRFSS, CDC NHANES/NHIS/NSFG, Census CPS+SIPP, HRSA NSCH.",
    "pack.healthcare_access": "Providers, access, and coverage: AHRQ NHQDR, CDC PLACES, CMS CCIIO/data/marketplace/medicaid/synpuf, HRSA AHRF+HPSA+UDS, Open Payments.",
    "pack.health_access_helpers": "Public reference and access helper pages: NIH USRDS, NLM VSAC. No restricted data wrappers.",
    "pack.environment_climate": "Climate, air, energy, hazards: NOAA, USGS earthquakes, EPA AQS, AirNow, EPA ECHO, EIA, NREL alt fuel, FEMA disasters.",
    "pack.global_governance": "Democracy, rule of law, corruption, peace: V-Dem, WGI, WJP, RSF press freedom, TI CPI, Fragile States Index, Global Peace Index, UN e-gov.",
    "pack.global_development": "Development indices, aid, climate vulnerability: UNDP HDR, SDG Index, OECD SDMX, OECD DAC CRS, IATI, IMF CDIS, ND-GAIN.",
    "pack.global_data_hubs": "Cross-cutting platforms: Our World in Data charts + catalog, Overture Maps.",
    "pack.global_surveys": "International survey microdata and catalogs: World Values Survey, Pew Global, ATUS, BRFSS.",
    "pack.international_core": "Best-of curated international set: World Bank, V-Dem, WGI, UNDP HDR, TI CPI, OWID charts, OECD SDMX.",
    "pack.geospatial": "Satellite, country boundaries, earth science: Natural Earth, Google Earth Engine, Microsoft Planetary Computer, NASA Earthdata, Overture Maps.",
    "pack.provider_kits": "Legacy provider-kit bundle: World Bank, NYC Open Data, FEC, CDC, BLS.",
}
